spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: database_sa_account
    password: 0CK3hEpgqBytyr91r5C0

  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect

  rabbitmq:
    host: localhost
    port: 5672
    username: rabbit_mq_sa_account
    password: LzHxPNqbptNuzgNiwZ51

rabbitmq:
  queue: browserWebHookQueue
  exchange: browserWebHookExchange
  routingkey: browserWebHookRouteKey

logging:
  level:
    root: ERROR
    org.springframework.web: ERROR
    uk.co.wh.sportsbook: DEBUG
    org.hibernate: ERROR


